version: '3'

services:
  example-service:
    build: .
    volumes:
      - .:/home/hardcoder/Desktop/docker-info-examples/node-with-docker
      - /home/hardcoder/Desktop/docker-info-examples/node-with-docker/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm start